Screensharing and camera video
AgoraIO/Docs-Source pull request #1001
Opened 2022-12-12 09:14 UTC by Kishan-Dhakan

- Resolves #976 
- Build example: 
![image](https://user-images.githubusercontent.com/42718091/207006806-4375104e-eebf-4b4d-8b8b-d03a22f67c39.png)

2022-12-14 09:20 UTC, billy-the-fish requested changes
You need to add words to the doc explaining that you can scare the screen and local video at the same time.

2022-12-30 15:11 UTC, atovpeko requested changes

2022-12-30 15:11 UTC, atovpeko commented on shared/video-sdk/develop/product-workflow/project-implementation/react-native.mdx
> +* A separate `SurfaceView` to render the screensharing. This will enable you to share your screen while also keeping your local video published.
```suggestion
* A separate `SurfaceView` to render the screen sharing. This enables you to share your screen while also keeping your local video published.
```

2022-12-30 15:11 UTC, atovpeko commented on shared/video-sdk/develop/product-workflow/project-implementation/react-native.mdx
> +    An `IRtcEngine` object can publish only one video track at a time. If you want to enable both screen sharing and video on one host, you need to create an IRtcEngineEx object: which enables publis
```suggestion
    An `IRtcEngine` object can publish only one video track at a time. If you want to enable both screen sharing and video on one host, create an `IRtcEngineEx` object to publish the video track from the camera, and one to publish the video track for screen sharing. To publish screen and camera streams simultaneously, take the following steps:
```

2023-01-02 12:38 UTC, atovpeko approved these changes

2023-01-03 08:55 UTC, merged