1038 Update Integrate Flexible Classroom changes.
AgoraIO/Docs-Source pull request #1057
Opened 2022-12-26 17:28 UTC by nirm2009

Integrate Flexible Classroom document updates for Android, iOS, Web, and Electron platforms.

2022-12-27 15:04 UTC, atovpeko requested changes
Please address a few minor language things.

2022-12-29 19:30 UTC, nirm2009 commented on shared/flexible-classroom/integrate-flexible-classroom/electron.mdx
>  4. Import the Agora Classroom SDK in the HTML file and launch a classroom:
Hello @atovpeko,
I'm afraid it is impossible in MDX to place a variable within quotes. As a workaround, may I suggest we replace "3.5.1-build.1116" with <build version>?

2022-12-29 19:30 UTC, nirm2009 commented on shared/flexible-classroom/integrate-flexible-classroom/ios.mdx
> +    - Replace the `AgoraEduCore` class with the `AgoraEduCorePuppet` class.
Hey @atovpeko, thanks for the suggestions! I changed the section to use a numbered list. The last bullet was mentioned as the last step for both Swift and Objective-C (before my changes on this PR), so if it's alright, I think we should keep it this way.

2022-12-30 12:02 UTC, atovpeko commented on shared/flexible-classroom/integrate-flexible-classroom/electron.mdx
>  4. Import the Agora Classroom SDK in the HTML file and launch a classroom:
Oh no, I meant for Classroom SDK, if there is one :-)

2022-12-30 12:09 UTC, atovpeko approved these changes

2022-12-30 14:06 UTC, merged