Proctor exams online - new doc
AgoraIO/Docs-Source pull request #1074
Opened 2022-12-29 13:18 UTC by atovpeko

2023-01-11 11:16 UTC, billy-the-fish requested changes
Nearly there.

2023-01-11 11:16 UTC, billy-the-fish commented on flexible-classroom/develop/supervise-exams-online.mdx
> +   Once hardware is successfully tested, click **Next step** to enter the room.
This is a step.

1. Click **Next step** and enter the room.

2023-01-11 11:16 UTC, billy-the-fish commented on flexible-classroom/develop/supervise-exams-online.mdx
> +4. After you enter the room, the exam will start automatically at the preset time. You can also click **Start Exam**
This is not a step, this is an explanation of what happens.

Will: please remove any instance of this word and move to the present tense.

2023-01-11 11:16 UTC, billy-the-fish commented on flexible-classroom/develop/supervise-exams-online.mdx
> +   During the exam you will see monitor screens, or surveillance walls, for examinees. You can do the following:
This is a step. You need to indent the sub-bullets so they are part of the step.

2023-01-11 11:16 UTC, billy-the-fish commented on flexible-classroom/develop/supervise-exams-online.mdx
> +
Intro sentence, 

Same general thoughts as above.

2023-01-13 14:15 UTC, atovpeko commented on flexible-classroom/develop/supervise-exams-online.mdx
> +The following example uses the <Vg k="FC"/> web demo to illustrate how examinees and examiners use the online
Changed this into completely because it turned out to be the same as the intro to the page

2023-01-13 14:35 UTC, atovpeko commented on flexible-classroom/develop/supervise-exams-online.mdx
> +|Role     |Prerequisites|
Did for all but one (features), where it just doesn't work as a list because it's more table data

2023-01-16 11:43 UTC, billy-the-fish approved these changes
LGTM.

2023-01-16 16:06 UTC, merged