1017 create the Android authentication guide for MA
AgoraIO/Docs-Source pull request #1107
Opened 2023-01-11 10:19 UTC by saudsami

2023-01-24 09:01 UTC, billy-the-fish requested changes
Ok, so, for Android embedded it works in exactly the same way as normal android, right? 

Couple of small comments, plus, the link to the token generator page does not work, you need to add the doc to this product.

2023-01-24 17:18 UTC, saudsami commented on shared/variables/global.js
> +export const MA_SDK_API_REF_ROOT = `https://docs.agora.io/cn/RTSA/API%20Reference`;
Yes, It is very similar to the Video SDK Android implementation.

2023-01-25 03:14 UTC, saudsami commented on shared/video-sdk/_authentication-workflow.mdx
>  To follow this procedure the reader is suggested to have:
Fixed

2023-01-25 03:14 UTC, saudsami commented on shared/variables/product.js
> +    SDK: 'RTSA SDK',
fixed

2023-01-28 10:24 UTC, merged