Add/release notes 1.1.0
AgoraIO/Docs-Source pull request #1206
Opened 2023-02-21 09:29 UTC by Kishan-Dhakan

- Resolves #1121

2023-02-28 14:03 UTC, atovpeko requested changes
Please:
1. Address my comments
2. Ping the CN writer for updated RNs (to remove the `XXX`)
Thank you

2023-02-28 14:03 UTC, atovpeko commented on shared/chat-sdk/client-api/messages/send-receive-messages/project-implementation/ios.mdx
> +### Set message priority
Please apply my suggestion for the same intro in Android

2023-02-28 14:03 UTC, atovpeko commented on shared/chat-sdk/client-api/messages/send-receive-messages/project-implementation/web.mdx
> +
Please apply my suggestion for the same intro in Android

2023-03-02 08:13 UTC, Kishan-Dhakan commented
@atovpeko I've resolved the comments and pinged the CN writer on the original issue.

2023-03-03 14:12 UTC, atovpeko approved these changes
I am approving this hoping the `XXX` blanks will be fixed before this is merged

2023-03-07 02:49 UTC, Kishan-Dhakan commented
@atovpeko merging this after discussing with Iain, when the new RNs are available I'll update it in a separate PR.

2023-03-07 02:57 UTC, merged