Issue Template Updates
AgoraIO/Docs-Source pull request #1472
Opened 2023-09-26 10:57 UTC by maxxfrazer

- updated existing issues to show whether they are reserved for internal use.
- disabled blank issues.
- added SDK/Product section to doc update issue template.

2023-09-26 11:09 UTC, billy-the-fish requested changes

2023-09-26 11:09 UTC, billy-the-fish commented on .github/ISSUE_TEMPLATE/config.yml
> +  - name: SDK Bugs and Feature Requests
Sentence case please.

2023-09-26 11:09 UTC, billy-the-fish commented on .github/ISSUE_TEMPLATE/docs-update-issue.md
> +<!-- Signaling, Broadcast Streaming, Voice... -->
Hmmmmmm, by putting things all in comments it will take ages to make a lot of tickets. Could be better to have things to remove.

2023-09-26 11:09 UTC, billy-the-fish commented on .github/ISSUE_TEMPLATE/docs-update-issue.md
> +<!-- Anything else that will help with this issue? (eg Screenshots) -->
For example, not eg. 

(sorry, tickets for tech writers need to follow the style guide :-) )

2023-09-27 11:54 UTC, maxxfrazer commented
@billy-the-fish can I get an OK on this?

2023-09-27 12:11 UTC, billy-the-fish approved these changes
Ok

2023-09-27 12:12 UTC, merged