208 cloud proxy doc for electron
AgoraIO/Docs-Source pull request #210
Opened 2022-08-17 12:09 UTC by hussain-khalid

2022-08-22 06:27 UTC, Kishan-Dhakan requested changes
MInor changes requested, LGTM otherwise

2022-08-22 06:27 UTC, Kishan-Dhakan commented on shared/video-sdk/develop/cloud-proxy/project-setup/electron.mdx
> +
In docs/shared/video-sdk/develop/_cloud-proxy.mdx (not changed as a part of this PR but still can be fixed in this) `[<Vpl k="CONSOLE" />]` is not rendering and needs to be changed to `[<Vg k="CONSOLE" />]`

2022-08-22 06:27 UTC, Kishan-Dhakan commented on shared/video-sdk/develop/cloud-proxy/project-implementation/electron.mdx
> +    In `preload.js`, add the following before `createAgoraRtcEngine`:
Missing comma in `createAgoraRtcEngine`, i.e., it should be ``createAgoraRtcEngine,`.

2022-08-28 15:30 UTC, billy-the-fish approved these changes

2022-08-29 09:56 UTC, hussain-khalid commented on shared/video-sdk/get-started/get-started-sdk/project-implementation/electron.mdx
> +            <title>Get started with <Vpd k="PRODUCT" /></title>
i have removed these variables already.

2022-08-29 18:12 UTC, merged