add channel encryption for ILS, Video and voice
AgoraIO/Docs-Source pull request #292
Opened 2022-08-31 08:00 UTC by Kishan-Dhakan

Review these:
- http://localhost:3000/voice-calling/develop/media-stream-encryption?platform=react-native
- http://localhost:3000/video-calling/develop/media-stream-encryption?platform=react-native
- http://localhost:3000/interactive-live-streaming/develop/media-stream-encryption?platform=react-native

I have validated the code on android. Please note that the encryption modes `Aes128Gcm2` and `Aes256Gcm2` are returning -2 which is why I have used another encryption mode so that this sample code works as is.

2022-09-05 08:28 UTC, billy-the-fish requested changes
Nearly there, good work.

2022-09-05 08:28 UTC, billy-the-fish commented on shared/video-sdk/encrypt-media-streams/project-implementation/react-native.mdx
> +    1. Create an object of `EncryptionConfig` class and specify a configuration for the channel encryption. In the configuration, you specify `encryptionMode`, `encryptionKey`, and `encryptionKdfSalt
Create an `EncryptionConfig` instance. 

modes, it is optional for other encryption modes.

2022-09-05 08:28 UTC, billy-the-fish commented on shared/video-sdk/encrypt-media-streams/project-implementation/react-native.mdx
> +    2. Call `enableEncryption` and pass `true` and the `EncryptionConfig` object as parameters to enable media encryption.
\<what you are doing> \<how to do it>

To enable media encryption, call `enableEncryption` with your `EncryptionConfig` instance.

2022-09-05 08:28 UTC, billy-the-fish commented on shared/video-sdk/encrypt-media-streams/project-implementation/react-native.mdx
> +    <Vg k="COMPANY"/> recommends using `Aes128Gcm2` or `Aes256Gcm2` encrypted mode. These two modes support the use of salt for higher security.
Please don't:
* Say Agora recommends, always "best practice"
* Put the number of items you are about to talk about. Chances are you will add or remove an item and forget about the number. Keep it simple. 

Best practice is to use  `Aes128Gcm2` or `Aes256Gcm2`. These modes use salt for higher security.

2022-09-05 08:28 UTC, billy-the-fish commented on shared/video-sdk/encrypt-media-streams/project-test/react-native.mdx
> +    1. Enable the Developer options on your Android device, and then connect it to your computer using a USB cable.
, then connect it

2022-09-05 08:28 UTC, billy-the-fish commented on shared/video-sdk/encrypt-media-streams/project-test/react-native.mdx
> +    1. Click the Build and run button in Xcode.
In Xcode, run your project. 


They are developers, they should have figured this one out :-).

2022-09-05 09:18 UTC, Kishan-Dhakan commented
@billy-the-fish, I resolved the comments.

2022-09-06 16:03 UTC, billy-the-fish approved these changes
Good work, thank you.

2022-09-07 08:02 UTC, merged