Multi channel rn
AgoraIO/Docs-Source pull request #326
Opened 2022-09-09 07:27 UTC by Kishan-Dhakan

- Multi channel (and media relay) doc for ILS-RN

2022-09-12 08:36 UTC, billy-the-fish requested changes
Good doc, just a few changes to make. 

It may be an idea to update the variable for the API ref in this pr, or merge the api ref url PR to main and merge back. 

Well done.

2022-09-12 08:36 UTC, billy-the-fish commented on shared/video-sdk/develop/live-streaming-over-multiple-channels/project-implementation/react-native.mdx
> +    To store source and destination channel settings and manage channel relay, in `App.tsx`, add the following variables to declarations:
to the declarations.

2022-09-12 08:36 UTC, billy-the-fish commented on shared/video-sdk/develop/live-streaming-over-multiple-channels/project-implementation/react-native.mdx
> +    To implement media relay, import the corresponding <Vg k="COMPANY" /> modules. In `App.tsx`, add the following imports before `createAgoraRtcEngine,`:
Always explain things in a chronological order. 

To implement media relay, in`App.tsx`,:
      1. Replace the `IRtcEngine` library with `IRtcEngineEx`.
      2. Add the following imports before `createAgoraRtcEngine,`:

             ```
               code
              ```

2022-09-12 08:36 UTC, billy-the-fish commented on shared/video-sdk/develop/live-streaming-over-multiple-channels/project-implementation/react-native.mdx
> +    To join and manage a second channel, in `App.tsx`, add the following variables to declarations:
to the declarations

2022-09-12 08:36 UTC, billy-the-fish commented on shared/video-sdk/develop/live-streaming-over-multiple-channels/project-implementation/react-native.mdx
> +
Please update the indenting for the substeps so the code is rendered inside the step and the numbering works. 

(The code example needs to have a space after the step and be indented )

2022-09-12 08:36 UTC, billy-the-fish commented on shared/video-sdk/develop/live-streaming-over-multiple-channels/project-implementation/react-native.mdx
> +    To see if you have successfully joined the second channel, update the `onJoinChannelSuccess` callback to print channel ID from the connection:
to print the channel ID for the connection.

2022-09-12 08:36 UTC, billy-the-fish commented on shared/video-sdk/develop/live-streaming-over-multiple-channels/project-test/react-native.mdx
> +4. In your browser, navigate to the <Link target="_blank" to="{{Global.DEMO_BASIC_VIDEO_CALL_URL}}"><Vg k="COMPANY" />web demo</Link> and update _App ID_, _Channel_, and _Token_ with the values for y
Please add a space after the <Vg k="COMPANY" /> variable. It reads as Agoraweb demo..

2022-09-12 08:36 UTC, billy-the-fish commented on shared/video-sdk/develop/live-streaming-over-multiple-channels/project-test/react-native.mdx
> +5. Repeat the previous step on a second device, but this time use `appId`, `destChannelName`, and `destChannelToken` to **Join** the channel.
On another device, update  _App ID_, _Channel_, and _Token_ with the `appId`, `destChannelName`, and `destChannelToken`  values.

2022-09-12 08:36 UTC, billy-the-fish commented on shared/video-sdk/develop/live-streaming-over-multiple-channels/project-test/react-native.mdx
> +4. In your browser, navigate to the <Link target="_blank" to="{{Global.DEMO_BASIC_VIDEO_CALL_URL}}"><Vg k="COMPANY" />web demo</Link> and update _App ID_, _Channel_, and _Token_ with the values for y
Space for Agora web demo

2022-09-13 09:38 UTC, Kishan-Dhakan commented
@billy-the-fish I have resolved the comments.

2022-09-13 13:03 UTC, merged