445 catch up updates analytics
AgoraIO/Docs-Source pull request #453
Opened 2022-09-27 09:31 UTC by FayHaifei

2022-09-27 10:58 UTC, dengyaxi commented
- [ ] 左侧目录需要按 issue 里的样子调整
- [ ] Chat 那两篇内容没有迁移，要加一下，Chat 的目录下应该已经迁移过了

2022-09-27 17:09 UTC, billy-the-fish requested changes
Not sure what has happened, but when I run this locally all the platform buttons have disappeared. Can you fix it and try again please.

2022-09-28 02:42 UTC, dengyaxi commented
There are no platform buttons because Analytics applies to all platforms. Similar to what we have decided for Media Push and Pull.

2022-09-28 03:23 UTC, dengyaxi commented on shared/variables/product.js
> +  'agora-analytics': {
The previous variable you used does not work. That's why we changed it. It needs to be consistent with the product id that Shuvo defines here: https://github.com/AgoraIO/Docs/blob/main/data/products.js

We've tested it locally and it works fine

2022-09-28 07:11 UTC, billy-the-fish commented on shared/variables/product.js
> +  'agora-analytics': {
:-D

2022-09-28 07:11 UTC, billy-the-fish approved these changes

2022-09-28 08:22 UTC, dengyaxi approved these changes

2022-09-28 08:24 UTC, merged