660 spatial audio implementation for web
AgoraIO/Docs-Source pull request #870
Opened 2022-11-11 09:45 UTC by saudsami

closes #660 
closes #761

2022-11-15 12:44 UTC, billy-the-fish requested changes
I've left a few comments. As a global idea, please have another look a the Android guide and update to match.

2022-11-15 12:44 UTC, billy-the-fish commented on shared/video-sdk/develop/spatial-audio/project-implementation/web.mdx
> +1. Call [`createProcessor`](#createprocessor) to create a `SpatialAudioProcessor` instance.
So? 

Where is the code example, this does not fit the pattern. 

. Some kind of explanation
   code example. 


I'm stopping here. Can you have a quick look at the Android guide and update to look like that. Soon as that is done I will review again.

2022-11-15 15:04 UTC, billy-the-fish commented
Can you have a look at the code in https://github.com/AgoraIO/Docs-Source/issues/894 as an idea on how to update this so the spatial audio feature is easier to detect.

2022-11-17 11:12 UTC, saudsami commented on shared/video-sdk/develop/_spatial-audio.mdx
> +<PlatformWrapper platform='web'>
done

2022-11-17 11:16 UTC, saudsami commented on shared/video-sdk/develop/spatial-audio/project-setup/web.mdx
> +    1.	Add the following code to your  `.js` file to import the spatial audio module:
done.

2022-11-17 11:18 UTC, saudsami commented on shared/video-sdk/develop/spatial-audio/project-setup/web.mdx
> +    1.	Run the following command to install the spatial audio plugin:
done

2022-11-17 11:45 UTC, saudsami commented on shared/video-sdk/develop/spatial-audio/project-setup/web.mdx
> +    1.	Publish the Wasm and JS files in the  `node_modules/agora-extension-spatial-audio/external` directory to a CDN or static resource server, and ensure that they are in the same public path. When
done

2022-11-17 16:43 UTC, saudsami commented on shared/video-sdk/develop/spatial-audio/project-setup/web.mdx
> +        * Versions greater than or equal to Chrome 97 and Edge 97: Add `script-src` in options `wasm-unsafe-eval`. For example:
done

2022-11-17 16:45 UTC, saudsami commented on shared/video-sdk/develop/spatial-audio/project-setup/web.mdx
> +    Call the `AgoraRTC.registerExtensions` method and pass in the created  `SpatialAudioExtension` instance.
done

2022-11-18 15:13 UTC, merged