882 all platforms leavechannelex updated
AgoraIO/Docs-Source pull request #968
Opened 2022-12-04 07:29 UTC by hussain-khalid

2022-12-05 13:40 UTC, billy-the-fish commented
Can you sort out the conflicts and sort out the DRM changes you have in here.

2022-12-09 13:19 UTC, atovpeko requested changes
Just a few language things

2022-12-09 13:19 UTC, atovpeko commented on shared/extensions-marketplace/drm-play/project-test/electron.mdx
> +3.  In **preload.js**, update `appID`, `channel` and `token` with your values.
```suggestion
3.  In **preload.js**, update `appID`, `channel`, and `token` with your values.
```

2022-12-09 13:19 UTC, atovpeko commented on shared/video-sdk/develop/ensure-channel-quality/project-implementation/electron.mdx
> +    To customize the location, content and size of log files, in `preload.js`, add the following code to `window.onload()` before `agoraEngine.registerEventHandler(EventHandles);`:
```suggestion
    To customize the location, content, and size of log files, in `preload.js` add the following code to `window.onload()` before `agoraEngine.registerEventHandler(EventHandles);`:
```

2022-12-09 13:19 UTC, atovpeko commented on shared/video-sdk/develop/ensure-channel-quality/project-implementation/electron.mdx
> +    To specify the audience latency level, in `preload.js`, add the following code after `if (document.getElementById('host').checked) {`:
```suggestion
    To specify the audience latency level, in `preload.js` add the following code after `if (document.getElementById('host').checked) {`:
```

2022-12-20 15:23 UTC, merged